# Generated by Django 4.2.10 on 2024-02-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosso', '0005_userprofile_firstname_userprofile_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
    ]
