# Generated by Django 4.2.10 on 2024-02-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosso', '0006_remove_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dateOfBirth',
        ),
    ]
